version: '3'

networks:
  app-network:
    driver: bridge

services:

  server:
    build: ./
    depends_on:
      - redis
    ports:
      - "5000:5000"
    devices:
      - "/dev/vchiq:/dev/vchiq"
    networks:
      - app-network
    restart: on-failure
    
  
  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network
    restart: on-failure
