version: '3'
services:

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    volumes:
      - './redis/redis_data/:/bitnami/redis/data'
    restart: on-failure
  
  sender:
    build: sender/.
    depends_on:
      - redis
    restart: on-failure
  
  server:
    build: server/.
    depends_on:
      - redis
    volumes:
      - ./yaml/:/code/yaml/
    ports:
     - "5000:5000"
    restart: on-failure
  
  telegram-cli:
    build: telegram-cli/.
    depends_on:
      - server
    volumes:
      - ./yaml/:/app/yaml/
  
  dashboard:
    build: dashboard/.
    depends_on:
      - redis
    ports:
    - "9181:9181"
    restart: on-failure

volumes:
  redis_data:
    driver: local