version: '3'
services:

  server:
    build: ./
    depends_on:
      - redis
    restart: on-failure
    ports:
      - "5000:5000"
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    restart: on-failure